baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Thomas Mongstad'
theme = 'PaperMod'

enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true

buildDrafts = false
buildFuture = false
buildExpired = false

pagination.paperSize = 15
summaryLength = 70

# Permalinks?

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

